"""Name playable Chinese strategic regions after representative local settlements.
This changes labels/anchors only, preserves unit IDs, and checks every city lies
inside its region. Run after build_atlas.py or import apply_city_names(atlas).
PYTHONPATH=/private/tmp/shanhe-gis-deps python3 scripts/name_strategic_regions.py
"""
from pathlib import Path
import io,json,re,zipfile
import shapefile
from shapely.geometry import Polygon,Point
from shapely import make_valid
from pyproj import Transformer

ROOT=Path(__file__).resolve().parents[1]
T=Transformer.from_crs(4326,'+proj=laea +lat_0=30 +lon_0=105 +datum=WGS84 +units=m +no_defs',always_xy=True)
# Entries follow stable unit IDs, never their display labels. Modern names are
# lookup aliases for coordinates, not assertions of modern administrative status.
NAMES={
 'xinjiang':'伊宁 哈密=伊州区 喀什 承化=阿勒泰 迪化=乌鲁木齐 和田',
 'tibet':'日喀则 噶大克 萨嘎 拉萨 黑河=那曲镇 改则',
 'xikang':'昌都 丁青 康定 贡布江达 甘孜 巴塘',
 'yunnan':'思茅 昭通 昆明 大理',
 'gansu':'兰州 敦煌 张掖 天水',
 'ningxia':'宁夏=银川 达来库布 定远营 阿拉腾敖包',
 'qinghai':'拉加 杂多 鱼卡 玉树=结古街道 都兰 西宁',
 'shaanxi':'西安 榆林 汉中 韩城',
 'sichuan':'宜宾 西昌 重庆 成都',
 'guizhou':'都匀 安顺 铜仁 贵阳',
 'guangxi':'柳州 百色 桂林 南宁',
 'hubei':'荆州 宜昌 襄阳 武昌=武汉',
 'henan':'商丘 信阳 洛阳 郑州',
 'anhui':'合肥 安庆 蚌埠 芜湖',
 'jiangxi':'吉安 赣县=赣州 上饶 南昌',
 'hunan':'衡阳 郴县=郴州 芷江=芷江镇 长沙',
 'shanxi':'长治 大同 临汾 太原',
 'heilongjiang':'齐齐哈尔 海拉尔=海拉尔区 根河 铁骊=铁力',
 'jilin':'牡丹江 佳木斯 哈尔滨 延吉',
 'liaoning':'奉天=沈阳 洮南 锦州 通化',
 'rehe':'赤峰 开鲁=开鲁县 朝阳 承德',
 'chahar':'多伦 贝子庙=锡林浩特 赛罕塔拉 张家口',
 'suiyuan':'归绥=呼和浩特 五原 盐池 集宁',
 'jiangsu':'南京 徐州 苏州 盐城',
 'hebei':'保定 唐山 邯郸 北平=北京',
 'zhejiang':'杭州 宁波 金华 温州',
 'guangdong':'广州 崖县=三亚 汕头 钦县=钦州',
 'fujian':'泉州 福州 厦门 南平',
 'shandong':'济南 青岛 济宁 潍县=潍坊'
}
# Approximate settlement reference points where Natural Earth lacks a point or
# uses a newer urban centre. These are label anchors, never boundary controls.
EXTRA={
 '噶大克':(80.367,31.708),'萨嘎':(85.234,29.329),'改则':(84.062,32.304),
 '丁青':(95.598,31.412),'康定':(101.962,30.050),'贡布江达':(93.246,29.882),
 '甘孜':(99.99,31.622),'巴塘':(99.111,30.007),
 '达来库布':(101.055,41.959),'定远营':(105.670,38.833),'阿拉腾敖包':(103.182,40.322),
 '拉加':(100.695,34.682),'杂多':(95.299,32.891),'鱼卡':(95.554,38.596),
 '都匀':(107.518,26.259),'百色':(106.615,23.902),
 '多伦':(116.477,42.199),'赛罕塔拉':(112.658,42.742),
 '五原':(108.267,41.095),'盐池':(107.410,37.786),'集宁':(113.116,41.035),
 '崖县':(109.168,18.350),'武昌':(114.302,30.545)
}

def screen(lon,lat):
 x,y=T.transform(lon,lat);return [round(x/10000+1000,3),round(700-y/10000,3)]

def geometry(p):
 # Generator emits linear closed rings; even/odd SVG rule defines holes.
 rings=[make_valid(Polygon([tuple(map(float,c.split(','))) for c in r.split('L')])) for r in re.findall(r'M([^Z]+)Z',p['path'])]
 g=rings[0]
 for ring in rings[1:]:g=g.symmetric_difference(ring)
 return g

def places():
 z=zipfile.ZipFile(ROOT/'previews/historical-atlas-v3/source/ne-populated-places.zip')
 def f(s):return io.BytesIO(z.read(next(n for n in z.namelist() if n.endswith(s))))
 reader=shapefile.Reader(shp=f('.shp'),shx=f('.shx'),dbf=f('.dbf'),encoding='utf-8')
 result={}
 for record in reader.iterShapeRecords():
  p=record.record.as_dict()
  if p.get('ADM0_A3')!='CHN':continue
  result.setdefault(p.get('NAME_ZH'),[]).append(tuple(record.shape.points[0]))
 return result

def apply_city_names(atlas):
 lookup=places();s=atlas['scenarios']['asia'];report=[]
 for p in s['units']:
  if not p['id'].startswith('cn-'):continue
  if p['id']=='cn-shanghai-city':name,alias='上海','上海'
  else:
   key,i=p['id'][3:].rsplit('-',1);entry=NAMES[key].split()[int(i)-1];pair=entry.split('=');name,alias=pair[0],pair[-1]
  g=geometry(p);options=[EXTRA[name]] if name in EXTRA else lookup.get(alias,[])
  point=next((ll for ll in options if g.covers(Point(*screen(*ll)))),None)
  if point is None:raise ValueError(f"Representative city missing/outside region: {p['id']} {name} ({alias})")
  old=p['name'];x,y=screen(*point);p.update(name=name,x=x,y=y,representativeCity={'name':name,'lon':point[0],'lat':point[1],'x':x,'y':y,'modernAlias':alias})
  p['search']=list(dict.fromkeys([*p.get('search',[]),old,name,alias]))
  # Idempotent for standalone relabel + complete rebuild.
  p['note']=p['note'].split('代表地名：',1)[0]+f'代表地名：{name}。它指本地块内的代表城市或聚落，不等于该城市的历史市界；战略边界精度以原底本说明为准。'
  if not any(c['name']==name for c in s['cities']):s['cities'].append({'name':name,'lon':point[0],'lat':point[1],'x':x,'y':y,'importance':1})
  report.append({'id':p['id'],'name':name,'parent':p['parent'],'inside_region':True})
 assert len(report)==sum(len(v.split()) for v in NAMES.values())+1
 assert not any('分区' in p['name'] for p in s['units'] if p['id'].startswith('cn-'))
 return report

if __name__=='__main__':
 file=ROOT/'maps/atlas.js';atlas=json.loads(file.read_text().split('window.SHANHE_ATLAS = ',1)[1].rstrip(';\n'))
 report=apply_city_names(atlas)
 file.write_text('/* Generated by scripts/build_atlas.py; licences and sources: maps/SOURCES.md */\nwindow.SHANHE_ATLAS = '+json.dumps(atlas,ensure_ascii=False,separators=(',',':'))+';\n')
 (ROOT/'maps/city-names.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
 print(f'Renamed {len(report)} strategic regions; all settlement anchors lie within their own region.')
